local helpers = require('spec.helpers')

describe('commands', function()
  before_each(function()
    helpers.reset_config()
  end)

  describe('setup', function()
    it('creates the :CI command', function()
      require('ci.commands').setup()
      local cmds = vim.api.nvim_get_commands({})
      assert.is_not_nil(cmds.CI)
    end)

    it('does not error on :CI', function()
      require('ci.commands').setup()
      assert.has_no.errors(function()
        vim.cmd('CI')
      end)
    end)
  end)
end)
