local helpers = require('spec.helpers')

describe('ci', function()
  before_each(function()
    helpers.reset_config()
  end)

  describe('setup', function()
    it('accepts no options', function()
      assert.has_no.errors(function()
        require('ci').setup()
      end)
    end)

    it('accepts a valid debug option', function()
      assert.has_no.errors(function()
        require('ci').setup({ debug = true })
      end)
    end)

    it('rejects a non-table opts', function()
      assert.has_error(function()
        require('ci').setup('nope')
      end)
    end)

    it('rejects a non-boolean debug', function()
      assert.has_error(function()
        require('ci').setup({ debug = 1 })
      end)
    end)
  end)
end)
